---
language: python
python: "2.7"

# Run jobs in containers.
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-virtualenv
      - realpath

# Create a build matrix for the different test jobs.
env:
  matrix:
    # Run python style checks.
    - TOX_ENV=pep8
    # Run python2.7 unit tests.
    - TOX_ENV=py27

install:
  - pip install tox

script:
  # Run the tox environment.
  - tox -e ${TOX_ENV}
