[metadata]
name = stackhpc-inspector-plugins
summary = StackHPC plugins for OpenStack ironic inspector
description-file = README.rst
author = StackHPC Ltd
author-email = mark@stackhpc.com
home-page = https://github.com/stackhpc/stackhpc-inspector-plugins
license = Apache-2
classifier =
    Environment :: Console
    Environment :: OpenStack
    Intended Audience :: System Administrators
    Intended Audience :: Information Technology
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[files]
packages =
    stackhpc_inspector_plugins

[entry_points]
ironic.inspection.hooks =
    ib_physnet = stackhpc_inspector_plugins.plugins.ib_physnet:IBPhysnetHook
    system_name_physnet = stackhpc_inspector_plugins.plugins.ib_physnet:SystemNamePhysnetHook
    port_groups = stackhpc_inspector_plugins.plugins.port_group:PortGroupsHook
